dofile (lfs.writedir() .. [[DCFS_Cap2_Syria\Scripts\System\]] .. "Graph.lua")
dofile (lfs.writedir() .. [[DCFS_Cap2_Syria\Scripts\System\]] .. "Graph_Path.lua")
dofile (lfs.writedir() .. [[DCFS_Cap2_Syria\Scripts\System\]] .. "Basic_Functions.lua")
dofile (lfs.writedir() .. [[DCFS_Cap2_Syria\Scripts\System\]] .. "Waypoint_Gen.lua")
dofile (lfs.writedir() .. [[DCFS_Cap2_Syria\Scripts\System\]] .. "Templates.lua")
dofile (lfs.writedir() .. [[DCFS_Cap2_Syria\Scripts\Zones\]] .. "Init.lua")
dofile (lfs.writedir() .. [[DCFS_Cap2_Syria\Scripts\AI_Ground\]] .. "Ground_Functions.lua")
dofile (lfs.writedir() .. [[DCFS_Cap2_Syria\Scripts\AI_Ground\]] .. "Init.lua")